FROM ubuntu:20.04

USER root
RUN set -ex && \
    apt-get update && apt-get install -y \
        bash \
        tzdata \
        curl \
        nano \
        wget \
        git \
        openssl \
        openssh-client \
        nodejs \
        ca-certificates && \
   

RUN apt-get update && apt-get install -y build-essential python && \
    node -v
    npm  install -g --unsafe-perm node-red
    npm uninstall node-red-node-gpio && \
EXPOSE 1880
RUN node-red


        
