version: '3.9'
services:
  mongodb:
    public: true
    container_name: mongodb
    image: docker.io/bitnami/mongodb:5.0
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGODB_ROOT_USER=${MONGODB_ROOT_USER}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_SYSTEM_LOG_VERBOSITY=${MONGODB_SYSTEM_LOG_VERBOSITY}
      - MONGODB_DISABLE_SYSTEM_LOG=${MONGODB_DISABLE_SYSTEM_LOG}
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'  
      
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  
  nr:
    public: true
    build: ./node-red1
    environment:
      - TZ=Asia/Tokyo
      - DB_HOST=mongodb://mongodb:27017
      - secret=dev
    ports:
      - 1880
    volumes:
      - node-red:/home/94r4d0x/.node-red
    links:
      - mongodb
      
  
  nsr1:
    public: true
    build: ./node-red1
    environment:
      - TZ=Asia/Tokyo
      - DB_HOST=mongodb://mongodb:27017
      - secret=dev
    ports:
      - 1880
    volumes:
      - nrsn1-drive:/home/94r4d0x/.node-red
    links:
      - mongodb
  
      
  nsr2:
    public: true
    build: ./node-red1
    environment:
      - TZ=Asia/Tokyo
      - DB_HOST=mongodb://mongodb:27017
      - secret=dev
    ports:
      - 1880
    volumes:
      - nrsn2-drive:/home/94r4d0x/.node-red
    links:
      - mongodb  
      
  nsr3:
    public: true
    build: ./node-red1
    environment:
      - TZ=Asia/Tokyo
      - DB_HOST=mongodb://mongodb:27017
      - secret=dev
    ports:
      - 1880
    volumes:
      - nrsn3-drive:/home/94r4d0x/.node-red
    links:
      - mongodb
  nsr4:
    public: true
    build: ./node-red1
    environment:
      - TZ=Asia/Tokyo
      - DB_HOST=mongodb://mongodb:27017
      - secret=dev
    ports:
      - 1880
    volumes:
      - nrsn4-drive:/home/94r4d0x/.node-red
    links:
      - mongodb
  nsr5:
    public: true
    build: ./node-red1
    environment:
      - TZ=Asia/Tokyo
      - DB_HOST=mongodb://mongodb:27017
      - secret=dev
    ports:
      - 1880
    volumes:
      - nrsn5-drive:/home/94r4d0x/.node-red
    links:
      - mongodb
  nsr6:
    public: true
    build: ./node-red1
    environment:
      - TZ=Asia/Tokyo
      - DB_HOST=mongodb://mongodb:27017
      - secret=dev
    ports:
      - 1880
    volumes:
      - nrsn6-drive:/home/94r4d0x/.node-red
    links:
      - mongodb
  nsr7:
    public: true
    build: ./node-red1
    environment:
      - TZ=Asia/Tokyo
      - DB_HOST=mongodb://mongodb:27017
      - secret=dev
    ports:
      - 1880
    volumes:
      - nrsn7-drive:/home/94r4d0x/.node-red
    links:
      - mongodb

   
 
      
volumes:
  node-red:
    size: 1Gi
  nrsn1-drive:
    size: 250Mi
  nrsn2-drive:
    size: 250Mi
  nrsn3-drive:
    size: 250Mi
  nrsn4-drive:
    size: 250Mi
  nrsn5-drive:
    size: 250Mi
  nrsn6-drive:
    size: 250Mi
  nrsn7-drive:
    size: 250Mi
  mongodb_data:
    driver: local
    size: 2Gi
    
networks:
  pic:
    driver: host
    

